<?php
/**
 * Profile API - View and Update Current User's Profile
 * backend/api/profile_api.php
 */

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(200);
    exit;
}

require_once '../config/database.php';

session_start();

// Auth guard
if (empty($_SESSION['logged_in'])) {
    jsonResponse(false, 'Unauthorized access', [], 401);
}

$method = $_SERVER['REQUEST_METHOD'];
$action = $_GET['action'] ?? null;

try {
    switch ($method) {
        case 'GET':
            if ($action === 'get') {
                getProfile();
            } else {
                jsonResponse(false, 'Invalid action');
            }
            break;

        case 'POST':
            $data = json_decode(file_get_contents('php://input'), true);
            if (!$data) {
                jsonResponse(false, 'Invalid JSON data');
            }

            $postAction = $data['action'] ?? null;

            if ($postAction === 'update_info') {
                updateProfileInfo($data);
            } elseif ($postAction === 'change_password') {
                changePassword($data);
            } else {
                jsonResponse(false, 'Invalid action');
            }
            break;

        default:
            jsonResponse(false, 'Method not allowed', [], 405);
    }
} catch (Exception $e) {
    error_log('Profile API Error: ' . $e->getMessage());
    jsonResponse(false, 'Server error occurred', [], 500);
}

/**
 * Get current logged-in user's profile
 */
function getProfile(): void {
    $userId = $_SESSION['user_id'] ?? 0;

    if ($userId <= 0) {
        jsonResponse(false, 'Invalid session');
    }

    $conn = getDBConnection();
    $stmt = $conn->prepare("
        SELECT user_id, username, full_name, email, role, is_active, created_at
        FROM qa_users
        WHERE user_id = ?
    ");
    $stmt->bind_param('i', $userId);
    $stmt->execute();
    $result = $stmt->get_result();
    $user = $result->fetch_assoc();
    $stmt->close();

    if (!$user) {
        jsonResponse(false, 'User not found', [], 404);
    }

    // Attach activity summary
    $user['activity'] = getActivitySummary($userId);

    jsonResponse(true, 'Profile loaded', ['data' => $user]);
}

/**
 * Get a lightweight activity summary for the user
 */
function getActivitySummary(int $userId): array {
    $conn = getDBConnection();

    // Surveys created by the user
    $stmt = $conn->prepare("SELECT COUNT(*) as cnt FROM qa_surveys WHERE created_by = ?");
    $stmt->bind_param('i', $userId);
    $stmt->execute();
    $surveysCreated = (int) $stmt->get_result()->fetch_assoc()['cnt'];
    $stmt->close();

    // Reports generated by the user
    $stmt = $conn->prepare("SELECT COUNT(*) as cnt FROM qa_reports WHERE generated_by = ?");
    $stmt->bind_param('i', $userId);
    $stmt->execute();
    $reportsGenerated = (int) $stmt->get_result()->fetch_assoc()['cnt'];
    $stmt->close();

    return [
        'surveys_created'   => $surveysCreated,
        'reports_generated' => $reportsGenerated,
    ];
}

/**
 * Update full_name and email for the current user
 */
function updateProfileInfo(array $data): void {
    $userId = $_SESSION['user_id'] ?? 0;

    if ($userId <= 0) {
        jsonResponse(false, 'Invalid session');
    }

    $errors = validateProfileInfo($data);
    if (!empty($errors)) {
        jsonResponse(false, 'Validation failed', ['errors' => $errors]);
    }

    $fullName = trim($data['full_name']);
    $email    = trim($data['email']);

    $conn = getDBConnection();

    // Check email uniqueness (exclude current user)
    $stmt = $conn->prepare("SELECT user_id FROM qa_users WHERE email = ? AND user_id != ?");
    $stmt->bind_param('si', $email, $userId);
    $stmt->execute();
    if ($stmt->get_result()->num_rows > 0) {
        $stmt->close();
        jsonResponse(false, 'Validation failed', ['errors' => ['email' => 'Email is already in use by another account']]);
    }
    $stmt->close();

    $stmt = $conn->prepare("UPDATE qa_users SET full_name = ?, email = ? WHERE user_id = ?");
    $stmt->bind_param('ssi', $fullName, $email, $userId);

    if ($stmt->execute()) {
        // Refresh session values
        $_SESSION['full_name'] = $fullName;
        $_SESSION['email']     = $email;
        $stmt->close();
        jsonResponse(true, 'Profile updated successfully');
    } else {
        $stmt->close();
        jsonResponse(false, 'Failed to update profile');
    }
}

/**
 * Change the current user's password
 */
function changePassword(array $data): void {
    $userId = $_SESSION['user_id'] ?? 0;

    if ($userId <= 0) {
        jsonResponse(false, 'Invalid session');
    }

    $errors = validatePasswordChange($data);
    if (!empty($errors)) {
        jsonResponse(false, 'Validation failed', ['errors' => $errors]);
    }

    $conn = getDBConnection();

    // Fetch current hash
    $stmt = $conn->prepare("SELECT password_hash FROM qa_users WHERE user_id = ?");
    $stmt->bind_param('i', $userId);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();
    $stmt->close();

    if (!$row) {
        jsonResponse(false, 'User not found', [], 404);
    }

    if (!password_verify($data['current_password'], $row['password_hash'])) {
        jsonResponse(false, 'Validation failed', ['errors' => ['current_password' => 'Current password is incorrect']]);
    }

    $newHash = password_hash($data['new_password'], PASSWORD_BCRYPT);

    $stmt = $conn->prepare("UPDATE qa_users SET password_hash = ? WHERE user_id = ?");
    $stmt->bind_param('si', $newHash, $userId);

    if ($stmt->execute()) {
        $stmt->close();
        jsonResponse(true, 'Password changed successfully');
    } else {
        $stmt->close();
        jsonResponse(false, 'Failed to change password');
    }
}

/**
 * Validate profile info fields
 */
function validateProfileInfo(array $data): array {
    $errors = [];

    if (empty($data['full_name']) || trim($data['full_name']) === '') {
        $errors['full_name'] = 'Full name is required';
    } elseif (strlen($data['full_name']) > 100) {
        $errors['full_name'] = 'Full name must not exceed 100 characters';
    }

    if (empty($data['email']) || trim($data['email']) === '') {
        $errors['email'] = 'Email is required';
    } elseif (!filter_var($data['email'], FILTER_VALIDATE_EMAIL)) {
        $errors['email'] = 'Please enter a valid email address';
    } elseif (strlen($data['email']) > 100) {
        $errors['email'] = 'Email must not exceed 100 characters';
    }

    return $errors;
}

/**
 * Validate password change fields
 */
function validatePasswordChange(array $data): array {
    $errors = [];

    if (empty($data['current_password'])) {
        $errors['current_password'] = 'Current password is required';
    }

    if (empty($data['new_password'])) {
        $errors['new_password'] = 'New password is required';
    } elseif (strlen($data['new_password']) < 8) {
        $errors['new_password'] = 'New password must be at least 8 characters';
    }

    if (empty($data['confirm_password'])) {
        $errors['confirm_password'] = 'Please confirm your new password';
    } elseif (isset($data['new_password']) && $data['new_password'] !== $data['confirm_password']) {
        $errors['confirm_password'] = 'Passwords do not match';
    }

    if (isset($data['new_password']) && isset($data['current_password'])
        && $data['new_password'] === $data['current_password']) {
        $errors['new_password'] = 'New password must be different from the current password';
    }

    return $errors;
}